services:
  db:
    container_name: gpt-db
    image: postgres:15.8
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    command: postgres -c superuser_reserved_connections=0
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
