services:
  db-test:
    container_name: gpt-db-test
    image: postgres:15.8
    ports:
      - '54320:5432'
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
